### ISSUE TITLE
Applied Energistics 2

### ISSUE THREAD

**Issue by TheCodedOne** [CyanideX/Unity#105] opened 2017-01-27 17:20 UTC
I noticed there are textures in Unity for AE2 but since the latest AE2 for 1.10 switches to lowercase names, its textures in Unity don't work.

**Comment by engiwengi** [comment] 2017-02-11 11:16
While I'm not certain I managed to change every single texture's name over to the new format, this is what I've been using myself. Might have missed a few items and blocks, also didn't bother with any of the parts, and particles and such since it seemed that Unity's were the same as default textures. 

I'm assuming I'm allowed to upload this? Here it is: [appliedenergistics2.zip](https://github.com/CyanideX/Unity/files/768353/appliedenergistics2.zip)

**Comment by Aidoboy** [comment] 2017-02-15 14:44
Fork the repo, commit your changes, and submit a pull request.

**Comment by InsomniaKitten** [comment] 2017-03-21 21:53
Closing, duplicate of #110. Will be fixed soon.

**Closed by InsomniaKitten** 2017-03-21 21:53 UTC
