### ISSUE TITLE
Draconic Evolution Crystals invisible icons when using Unity.

### ISSUE THREAD

**Issue by desvandev** [CyanideX/Unity#167] opened 2018-05-22 05:37 UTC
Unity 1.6.3 - 1.12
DE 2.3.10.284
MC 1.12.2
FTB Revelation

**Comment by CyanideX** [comment] 2018-05-22 06:12
I'm not sure how that would be caused by Unity since we don't have support for that mod in our pack; no textures have been altered. 😕

**Comment by CyanideX** [comment] 2018-05-22 06:21
Works fine for me. Sorry, you're going to have to keep looking for the cause of the invisible crystals. 😞 

![2018-05-21_23 18 11](https://user-images.githubusercontent.com/3106700/40345253-4769d5d0-5d4d-11e8-804a-2008f44676cb.png)

![2018-05-21_23 21 57](https://user-images.githubusercontent.com/3106700/40345369-c96bbbd4-5d4d-11e8-8f3b-3dfda0c9ce37.png)

You could also try downloading Unity 1.12_plus from [here](https://github.com/CyanideX/Unity/tree/1.12_plus) on the off chance that something funky is going on with the Curse version.

**Comment by desvandev** [comment] 2018-05-22 16:52
I know that Unity doesn't modify Draconic Evolution textures, that's why I have no idea how to find/fix the problem lol.
Still the same problem with 1.12_plus:
![2018-05-22_13 46 45](https://user-images.githubusercontent.com/8462871/40377320-0657a764-5dc7-11e8-9c77-f3de51835b2b.png)
As you can (not) see, all of the DE "crystals" are blank, if I switch to default everything is ok. The models/textures once placed in the world are ok, it just the icons in JEI and inventory.

**Comment by ChloeDawn** [comment] 2018-05-22 17:34
Does this occur when loading other resource packs? Or only with Unity?

**Comment by CyanideX** [comment] 2018-05-22 17:35
Does this occur after you restart the game with Unity already enabled or just when applying it the first time in game?

Any chance you could go through the resource pack, deleting one folder at a time to see which one is causing this? You can delete advanced_machines first, for example, and then press F3+T in game to reload the pack.

**Comment by desvandev** [comment] 2018-05-23 01:32
I was about to test deleting each folder one by one but it takes ages for me to reload the resource pack. Investigating a little more I found a issue in CTM https://github.com/Chisel-Team/ConnectedTexturesMod/issues/34#issuecomment-350988494 with the same problem.
I don't know if this is something you guys can have a look or...

Anyway, thanks!

**Comment by ChloeDawn** [comment] 2018-05-23 01:42
@desvandev can you please try removing `CTP.zip` from your resource packs? That is loaded along with FTB Revelations if I'd read up correctly? And apparently that is the root cause.

**Comment by desvandev** [comment] 2018-05-23 01:49
There isn't a CTP.zip file 🤔Only Unity is there in the resource pack folder.

**Comment by ChloeDawn** [comment] 2018-05-23 01:51
Oh, nvm then, my bad... I'll look into this further tomorrow. I'm sure the issue is simple... it'll just be abstracted behind some annoying-to-read code.

**Comment by Fortist** [comment] 2018-06-28 12:45
It is simple, I figured it out a while ago.

DE looks for certain block textures, which if I recall is one of the CTM/Randomizing blocks, I think Glass.
You go into the blockstates of DE, find the energy crystal and change "textures" to
```
    "textures": {
      "all": "blocks/dirt"
    },
```
It's a fix. This also happens with YABBA as it only looks for vanilla textures, but that one is a bit more finicky to deal with

**Comment by ChloeDawn** [comment] 2018-06-28 13:12
This is an issue with CTM texture metadata not being handled correctly on the blocks in Draconic Evolution, or possibly due to CTM forcing a render layer. This can be resolved on our end by not defining data for the texture, but instead defining data for the models individually in our resource pack. I'll look into it soon.

**Comment by InsomniaKitten** [comment] 2018-06-28 14:06
On further testing, this issue seems tied to Connected Textures Pack, not Unity. I will do some further investigate, I'm pretty sure I know how to resolve this.

**Comment by ChloeDawn** [comment] 2018-06-28 14:14
This would actually be an issue for any resource pack adding CTM connected textures to the vanilla glass texture, so would be better resolved on Draconic Evolution's end by removing the dummy blockstate JSON. I'll make a pull request for it. Closing this for now, as it is not technically our issue.

**Closed as completed by ChloeDawn** 2018-06-28 14:14 UTC
Labels: bug, mod conflict
